algoritmo "SomaFuncao"
var
   V1, V2, s: Inteiro

Funcao Soma (x, y: Inteiro): Inteiro
Inicio
      Retorne x + y
FimFuncao
inicio
      Escreva ("Digite o primeiro valor: ")
      Leia (V1)
      Escreva ("Digite o segundo valor: ")
      Escreva ("Digite o segundo valor: ")
      Leia (V2)
      s <- Soma (V1, V2)
      Escreva ("A soma entre ", v1, " e ", V2, " e igual a ", s)
fimalgoritmo
